export const emoji_flags = [
  {"name":"Afghanistan","flag":"🇦🇫"},
  {"name":"Albania","flag":"🇦🇱"},
  {"name":"Algeria","flag":"🇩🇿"},
  {"name":"Andorra","flag":"🇦🇩"},
  {"name":"Angola","flag":"🇦🇴"},
  {"name":"Argentina","flag":"🇦🇷"},
  {"name":"Armenia","flag":"🇦🇲"},
  {"name":"Australia","flag":"🇦🇺"},
  {"name":"Austria","flag":"🇦🇹"},
  {"name":"Azerbaijan","flag":"🇦🇿"},
  {"name":"Bahamas","flag":"🇧🇸"},
  {"name":"Bahrain","flag":"🇧🇭"},
  {"name":"Bangladesh","flag":"🇧🇩"},
  {"name":"Belarus","flag":"🇧🇾"},
  {"name":"Belgium","flag":"🇧🇪"},
  {"name":"Brazil","flag":"🇧🇷"},
  {"name":"Canada","flag":"🇨🇦"},
  {"name":"China","flag":"🇨🇳"},
  {"name":"France","flag":"🇫🇷"},
  {"name":"Germany","flag":"🇩🇪"},
  {"name":"India","flag":"🇮🇳"},
  {"name":"Italy","flag":"🇮🇹"},
  {"name":"Japan","flag":"🇯🇵"},
  {"name":"Lithuania","flag":"🇱🇹"},
  {"name":"United Kingdom","flag":"🇬🇧"},
  {"name":"United States","flag":"🇺🇸"}
];